<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" layout="2columns" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <head>
        <title>
            Brand New Page
        </title>
    </head>    
    <body>
        <referenceContainer name="content">
            <block class="Magento\Framework\View\Element\Template" template="RCA_Newpage::main.phtml" />
        </referenceContainer>
    </body>
</page>